INSERT INTO provins VALUES('AB', 'Alberta');
INSERT INTO provins VALUES('BC', 'British Columbia');
INSERT INTO provins VALUES('MB', 'Manitoba');
INSERT INTO provins VALUES('NB', 'New Brunswick');
INSERT INTO provins VALUES('NL', 'Newfoundland and Labrador');
INSERT INTO provins VALUES('NT', 'Northwest Territories');
INSERT INTO provins VALUES('NS', 'Nova Scotia');
INSERT INTO provins VALUES('NU', 'Nunavut');
INSERT INTO provins VALUES('ON', 'Ontario');
INSERT INTO provins VALUES('PE', 'Prince Edward Island');
INSERT INTO provins VALUES('QC', 'Quebec');
INSERT INTO provins VALUES('SK', 'Saskatchewan');
INSERT INTO provins VALUES('YT', 'Yukon');
