INSERT INTO farge VALUES (1, 'natur');
INSERT INTO farge VALUES (2, 'hvete');
INSERT INTO farge VALUES (3, 'perlegrå');
INSERT INTO farge VALUES (4, 'mellomgrå');
INSERT INTO farge VALUES (5, 'brun');
INSERT INTO farge VALUES (6, 'koksgrå');
INSERT INTO farge VALUES (7, 'rubinrød');
INSERT INTO farge VALUES (8, 'lys rosa');
INSERT INTO farge VALUES (9, 'marineblå');
INSERT INTO farge VALUES (10, 'tåke');
INSERT INTO farge VALUES (11, 'påfuglblå');
INSERT INTO farge VALUES (12, 'mosegrønn');
INSERT INTO farge VALUES (13, 'orange');
INSERT INTO farge VALUES (14, 'lyng');
INSERT INTO farge VALUES (15, 'lilla tåke');
INSERT INTO farge VALUES (16, 'blå');
INSERT INTO farge VALUES (17, 'jeansblå');
INSERT INTO farge VALUES (18, 'morgentåke');
INSERT INTO farge VALUES (19, 'skogsgrønn');
INSERT INTO farge VALUES (20, 'burgunder');
INSERT INTO farge VALUES (21, 'sjøblå');
INSERT INTO farge VALUES (22, 'gul');
INSERT INTO farge VALUES (23, 'grå');
INSERT INTO farge VALUES (24, 'rosa');
INSERT INTO farge VALUES (25, 'bringebær');
INSERT INTO farge VALUES (26, 'beige');
INSERT INTO farge VALUES (27, 'sjøgrønn');
INSERT INTO farge VALUES (28, 'gråblå');
INSERT INTO farge VALUES (29, 'mauve');
INSERT INTO farge VALUES (30, 'salvie grønn');
INSERT INTO farge VALUES (31, 'sort');
INSERT INTO farge VALUES (32, 'blush');
INSERT INTO farge VALUES (33, 'rosa sand');
INSERT INTO farge VALUES (34, 'rosa marmor');
INSERT INTO farge VALUES (35, 'leire');
INSERT INTO farge VALUES (36, 'lys blå');
INSERT INTO farge VALUES (37, 'blåfugl');
INSERT INTO farge VALUES (38, 'elektrisk oransje');
INSERT INTO farge VALUES (39, 'magenta');
INSERT INTO farge VALUES (40, 'limonade');
INSERT INTO farge VALUES (41, 'søt orkide');
INSERT INTO farge VALUES (42, 'pistasjis');
INSERT INTO farge VALUES (43, 'papegøyegrønn');
INSERT INTO farge VALUES (44, 'crimson rød');
INSERT INTO farge VALUES (45, 'nordsjøen');
INSERT INTO farge VALUES (46, 'mørk oliven');
INSERT INTO farge VALUES (47, 'oregano');
INSERT INTO farge VALUES (48, 'antikk grønn');
INSERT INTO farge VALUES (49, 'eikenøtt');
INSERT INTO farge VALUES (50, 'ferskenrosa');
INSERT INTO farge VALUES (51, 'ørkenrose');
INSERT INTO farge VALUES (52, 'roseblad');
INSERT INTO farge VALUES (53, 'jordbæris');
INSERT INTO farge VALUES (54, 'søt aprikos');
INSERT INTO farge VALUES (55, 'lys beige');
INSERT INTO farge VALUES (56, 'kanel');
INSERT INTO farge VALUES (57, 'kornblå');
INSERT INTO farge VALUES (58, 'lys askebrun');
INSERT INTO farge VALUES (59, 'lys grå');
INSERT INTO farge VALUES (60, 'lys oliven');
INSERT INTO farge VALUES (61, 'lys sjøgrønn');
INSERT INTO farge VALUES (62, 'mørk askebrun');
INSERT INTO farge VALUES (63, 'mørk grå');
INSERT INTO farge VALUES (64, 'nougat');
INSERT INTO farge VALUES (65, 'olivenmelert');
INSERT INTO farge VALUES (66, 'peanøtt');
INSERT INTO farge VALUES (67, 'perlehvit');
INSERT INTO farge VALUES (68, 'petrol');
INSERT INTO farge VALUES (69, 'rosa lavendel');
INSERT INTO farge VALUES (70, 'rød');
INSERT INTO farge VALUES (71, 'rødbrun');
INSERT INTO farge VALUES (72, 'sennep');
INSERT INTO farge VALUES (73, 'sitron');
INSERT INTO farge VALUES (74, 'sjokolade');
INSERT INTO farge VALUES (75, 'toffee');
INSERT INTO farge VALUES (76, 'ametyst');
INSERT INTO farge VALUES (77, 'bringebær rose');
INSERT INTO farge VALUES (78, 'grønt gress');
INSERT INTO farge VALUES (79, 'gulgrønn');
INSERT INTO farge VALUES (80, 'hasselnøtt');
INSERT INTO farge VALUES (81, 'havtåke');
INSERT INTO farge VALUES (82, 'hvit');
INSERT INTO farge VALUES (83, 'jordbærkrem');
INSERT INTO farge VALUES (84, 'kamel');
INSERT INTO farge VALUES (85, 'korall');
INSERT INTO farge VALUES (86, 'lavendel frost');
INSERT INTO farge VALUES (87, 'lys lavendel');
INSERT INTO farge VALUES (88, 'lys nougat');
INSERT INTO farge VALUES (89, 'lys perlegrå');
INSERT INTO farge VALUES (90, 'malva');
INSERT INTO farge VALUES (91, 'mandel');
INSERT INTO farge VALUES (92, 'mineralblå');
INSERT INTO farge VALUES (93, 'mørk blush');
INSERT INTO farge VALUES (94, 'mørk eføy');
INSERT INTO farge VALUES (95, 'mørk grønn');
INSERT INTO farge VALUES (96, 'mørk indigo');
INSERT INTO farge VALUES (97, 'mørk turkis');
INSERT INTO farge VALUES (98, 'måneskinnsblå');
INSERT INTO farge VALUES (99, 'oker');
INSERT INTO farge VALUES (100, 'orangemelert');
INSERT INTO farge VALUES (101, 'rødmelert');
INSERT INTO farge VALUES (102, 'sitronpai');
INSERT INTO farge VALUES (103, 'sterk lime');
INSERT INTO farge VALUES (104, 'støvet orange');
INSERT INTO farge VALUES (105, 'støvrosa');
INSERT INTO farge VALUES (106, 'tomatrød');
INSERT INTO farge VALUES (107, 'turkis');
INSERT INTO farge VALUES (108, 'vildrose');
INSERT INTO farge VALUES (109, 'vinrød');
INSERT INTO farge VALUES (110, 'blå skumring');
INSERT INTO farge VALUES (111, 'brostein');
INSERT INTO farge VALUES (112, 'grønn');
INSERT INTO farge VALUES (113, 'grålilla');
INSERT INTO farge VALUES (114, 'isblå');
INSERT INTO farge VALUES (115, 'kalk');
INSERT INTO farge VALUES (116, 'kongeblå');
INSERT INTO farge VALUES (117, 'tåkerosa');
INSERT INTO farge VALUES (118, 'agategrønn');
INSERT INTO farge VALUES (119, 'akvamarin');
INSERT INTO farge VALUES (120, 'bark');
INSERT INTO farge VALUES (121, 'bringebær sorbet');
INSERT INTO farge VALUES (122, 'cookie dough');
INSERT INTO farge VALUES (123, 'denim jeans');
INSERT INTO farge VALUES (124, 'drue');
INSERT INTO farge VALUES (125, 'enhjørning');
INSERT INTO farge VALUES (126, 'fersken');
INSERT INTO farge VALUES (127, 'forglemmegei');
INSERT INTO farge VALUES (128, 'frostgrønn');
INSERT INTO farge VALUES (129, 'gammelrosa');
INSERT INTO farge VALUES (130, 'grizzlybjørn');
INSERT INTO farge VALUES (131, 'grå tåke');
INSERT INTO farge VALUES (132, 'gråbeige');
INSERT INTO farge VALUES (133, 'gråbrun');
INSERT INTO farge VALUES (134, 'guacamole');
INSERT INTO farge VALUES (135, 'gull');
INSERT INTO farge VALUES (136, 'gulrotkake');
INSERT INTO farge VALUES (137, 'havdypet');
INSERT INTO farge VALUES (138, 'havglass');
INSERT INTO farge VALUES (139, 'hvit tåke');
INSERT INTO farge VALUES (140, 'høyrød');
INSERT INTO farge VALUES (141, 'karamell');
INSERT INTO farge VALUES (142, 'karri');
INSERT INTO farge VALUES (143, 'kastanje');
INSERT INTO farge VALUES (144, 'kirsebær');
INSERT INTO farge VALUES (145, 'kirsebær rød');
INSERT INTO farge VALUES (146, 'kirsebærsorbet');
INSERT INTO farge VALUES (147, 'koboltblå');
INSERT INTO farge VALUES (148, 'lavendel');
INSERT INTO farge VALUES (149, 'lilla');
INSERT INTO farge VALUES (150, 'lys fersken');
INSERT INTO farge VALUES (151, 'lys jeansblå');
INSERT INTO farge VALUES (152, 'løvetann');
INSERT INTO farge VALUES (153, 'mandelrose');
INSERT INTO farge VALUES (154, 'marmor');
INSERT INTO farge VALUES (155, 'marsipan');
INSERT INTO farge VALUES (156, 'mintkrem');
INSERT INTO farge VALUES (157, 'mocca');
INSERT INTO farge VALUES (158, 'murstein');
INSERT INTO farge VALUES (159, 'mørk blå');
INSERT INTO farge VALUES (160, 'mørk blågrønn');
INSERT INTO farge VALUES (161, 'mørk jeansblå');
INSERT INTO farge VALUES (162, 'mørkegrå');
INSERT INTO farge VALUES (163, 'oliven');
INSERT INTO farge VALUES (164, 'pepperkorn');
INSERT INTO farge VALUES (165, 'perle');
INSERT INTO farge VALUES (166, 'pistasj');
INSERT INTO farge VALUES (167, 'pudder');
INSERT INTO farge VALUES (168, 'pudderrosa');
INSERT INTO farge VALUES (169, 'purple rain');
INSERT INTO farge VALUES (170, 'ravn');
INSERT INTO farge VALUES (171, 'rosa/lilla');
INSERT INTO farge VALUES (172, 'rosevann');
INSERT INTO farge VALUES (173, 'rust');
INSERT INTO farge VALUES (174, 'rød murstein');
INSERT INTO farge VALUES (175, 'sand');
INSERT INTO farge VALUES (176, 'sennepsgul');
INSERT INTO farge VALUES (177, 'sink');
INSERT INTO farge VALUES (178, 'sitrongress');
INSERT INTO farge VALUES (179, 'sjøstein');
INSERT INTO farge VALUES (180, 'skjell');
INSERT INTO farge VALUES (181, 'skogbrun');
INSERT INTO farge VALUES (182, 'småstein');
INSERT INTO farge VALUES (183, 'soft mint');
INSERT INTO farge VALUES (184, 'spinatpai');
INSERT INTO farge VALUES (185, 'sterk rosa');
INSERT INTO farge VALUES (186, 'stormblå');
INSERT INTO farge VALUES (187, 'støvet lilla');
INSERT INTO farge VALUES (188, 'stålgrå');
INSERT INTO farge VALUES (189, 'sølv');
INSERT INTO farge VALUES (190, 'tranebær');
INSERT INTO farge VALUES (191, 'tåkete syrin');
INSERT INTO farge VALUES (192, 'vaniljegul');
INSERT INTO farge VALUES (193, 'varm sjokolade');

SELECT * from farge