INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 1);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 1);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 1);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca Boucle', 1);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 1);
INSERT INTO garn_har_farge VALUES ('Drops', 'Wish', 1);
INSERT INTO garn_har_farge VALUES ('Drops', 'Belle', 1);
INSERT INTO garn_har_farge VALUES ('Drops', 'Big Merino', 1);
INSERT INTO garn_har_farge VALUES ('Drops', 'Bomull-Lin', 1);
INSERT INTO garn_har_farge VALUES ('Drops', 'Melody', 1);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 1);
INSERT INTO garn_har_farge VALUES ('Drops', 'Polaris', 1);
INSERT INTO garn_har_farge VALUES ('Drops', 'Puna', 1);
INSERT INTO garn_har_farge VALUES ('Drops', 'Soft Tweed', 1);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 1);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 1);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 2);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 2);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 2);
INSERT INTO garn_har_farge VALUES ('Drops', 'Wish', 2);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 3);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 3);
INSERT INTO garn_har_farge VALUES ('Drops', 'Melody', 3);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 3);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 3);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 4);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 4);
INSERT INTO garn_har_farge VALUES ('Drops', 'Wish', 4);
INSERT INTO garn_har_farge VALUES ('Drops', 'Polaris', 4);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 4);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 5);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 5);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca Boucle', 5);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 5);
INSERT INTO garn_har_farge VALUES ('Drops', 'Bomull-Lin', 5);
INSERT INTO garn_har_farge VALUES ('Drops', 'Puna', 5);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 5);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 6);
INSERT INTO garn_har_farge VALUES ('Drops', 'Big Merino', 6);
INSERT INTO garn_har_farge VALUES ('Drops', 'Puna', 6);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 7);
INSERT INTO garn_har_farge VALUES ('Drops', 'Polaris', 7);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 8);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 8);
INSERT INTO garn_har_farge VALUES ('Drops', 'Loves You 9', 8);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 9);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 9);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 9);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 9);
INSERT INTO garn_har_farge VALUES ('Drops', 'Wish', 9);
INSERT INTO garn_har_farge VALUES ('Drops', 'Belle', 9);
INSERT INTO garn_har_farge VALUES ('Drops', 'Big Merino', 9);
INSERT INTO garn_har_farge VALUES ('Drops', 'Loves You 9', 9);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 9);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 9);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 9);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 9);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 10);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 10);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 10);
INSERT INTO garn_har_farge VALUES ('Drops', 'Melody', 10);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 10);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 11);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 12);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 12);
INSERT INTO garn_har_farge VALUES ('Drops', 'Belle', 12);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 12);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 13);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 13);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 13);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 14);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 15);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 15);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 16);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 17);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 17);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 17);
INSERT INTO garn_har_farge VALUES ('Drops', 'Wish', 17);
INSERT INTO garn_har_farge VALUES ('Drops', 'Belle', 17);
INSERT INTO garn_har_farge VALUES ('Drops', 'Big Merino', 17);
INSERT INTO garn_har_farge VALUES ('Drops', 'Loves You 9', 17);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 17);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 17);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 17);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 18);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 19);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 19);
INSERT INTO garn_har_farge VALUES ('Drops', 'Big Merino', 19);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 19);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 19);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 20);
INSERT INTO garn_har_farge VALUES ('Drops', 'Wish', 20);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 20);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 21);
INSERT INTO garn_har_farge VALUES ('Drops', 'Loves You 9', 21);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 22);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 23);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca Boucle', 23);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 23);
INSERT INTO garn_har_farge VALUES ('Drops', 'Big Merino', 23);
INSERT INTO garn_har_farge VALUES ('Drops', 'Delight', 23);
INSERT INTO garn_har_farge VALUES ('Drops', 'Loves You 9', 23);
INSERT INTO garn_har_farge VALUES ('Drops', 'Melody', 23);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 23);
INSERT INTO garn_har_farge VALUES ('Drops', 'Puna', 23);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 23);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 24);
INSERT INTO garn_har_farge VALUES ('Drops', 'Loves You 9', 24);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 25);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 26);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 26);
INSERT INTO garn_har_farge VALUES ('Drops', 'Wish', 26);
INSERT INTO garn_har_farge VALUES ('Drops', 'Big Merino', 26);
INSERT INTO garn_har_farge VALUES ('Drops', 'Bomull-Lin', 26);
INSERT INTO garn_har_farge VALUES ('Drops', 'Loves You 9', 26);
INSERT INTO garn_har_farge VALUES ('Drops', 'Melody', 26);
INSERT INTO garn_har_farge VALUES ('Drops', 'Puna', 26);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 26);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 27);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 27);
INSERT INTO garn_har_farge VALUES ('Drops', 'Wish', 27);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 27);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 27);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 28);
INSERT INTO garn_har_farge VALUES ('Drops', 'Bomull-Lin', 28);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 29);
INSERT INTO garn_har_farge VALUES ('Drops', 'Wish', 29);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 30);
INSERT INTO garn_har_farge VALUES ('Drops', 'Wish', 30);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 30);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 30);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 31);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 31);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 31);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca Boucle', 31);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 31);
INSERT INTO garn_har_farge VALUES ('Drops', 'Belle', 31);
INSERT INTO garn_har_farge VALUES ('Drops', 'Big Merino', 31);
INSERT INTO garn_har_farge VALUES ('Drops', 'Bomull-Lin', 31);
INSERT INTO garn_har_farge VALUES ('Drops', 'Melody', 31);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 31);
INSERT INTO garn_har_farge VALUES ('Drops', 'Polaris', 31);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 31);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 31);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 31);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 32);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 32);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 32);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 33);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 34);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 35);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 36);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 36);
INSERT INTO garn_har_farge VALUES ('Drops', 'Melody', 36);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 36);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 37);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 38);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 39);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 39);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 40);
INSERT INTO garn_har_farge VALUES ('Drops', 'Big Merino', 40);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 40);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 41);
INSERT INTO garn_har_farge VALUES ('Drops', 'Melody', 41);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 41);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 41);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 41);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 42);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 42);
INSERT INTO garn_har_farge VALUES ('Drops', 'Big Merino', 42);
INSERT INTO garn_har_farge VALUES ('Drops', 'Melody', 42);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 42);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 42);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 43);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 43);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 43);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 44);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 45);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 45);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 46);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 47);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 48);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 49);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 50);
INSERT INTO garn_har_farge VALUES ('Drops', 'Melody', 50);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 51);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 52);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 52);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 53);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 54);
INSERT INTO garn_har_farge VALUES ('Drops', 'Air', 55);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca Boucle', 55);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 55);
INSERT INTO garn_har_farge VALUES ('Drops', 'Belle', 55);
INSERT INTO garn_har_farge VALUES ('Drops', 'Big Merino', 55);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 55);
INSERT INTO garn_har_farge VALUES ('Drops', 'Polaris', 55);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 56);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 57);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 58);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 59);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 59);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca Boucle', 59);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 59);
INSERT INTO garn_har_farge VALUES ('Drops', 'Wish', 59);
INSERT INTO garn_har_farge VALUES ('Drops', 'Bomull-Lin', 59);
INSERT INTO garn_har_farge VALUES ('Drops', 'Loves You 9', 59);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 59);
INSERT INTO garn_har_farge VALUES ('Drops', 'Puna', 59);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 59);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 60);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 61);
INSERT INTO garn_har_farge VALUES ('Drops', 'Melody', 61);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 61);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 62);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 63);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 63);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 63);
INSERT INTO garn_har_farge VALUES ('Drops', 'Loves You 9', 63);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 63);
INSERT INTO garn_har_farge VALUES ('Drops', 'Polaris', 63);
INSERT INTO garn_har_farge VALUES ('Drops', 'Puna', 63);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 64);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 64);
INSERT INTO garn_har_farge VALUES ('Drops', 'Puna', 64);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 65);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 66);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 67);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 68);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 68);
INSERT INTO garn_har_farge VALUES ('Drops', 'Belle', 68);
INSERT INTO garn_har_farge VALUES ('Drops', 'Melody', 68);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 69);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 70);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 70);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 70);
INSERT INTO garn_har_farge VALUES ('Drops', 'Glitter', 70);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 70);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 70);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 71);
INSERT INTO garn_har_farge VALUES ('Drops', 'Big Merino', 71);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 72);
INSERT INTO garn_har_farge VALUES ('Drops', 'Loves You 9', 72);
INSERT INTO garn_har_farge VALUES ('Drops', 'Melody', 72);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 73);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 74);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alaska', 75);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 76);
INSERT INTO garn_har_farge VALUES ('Drops', 'Loves You 9', 76);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 77);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 78);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 79);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 80);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 80);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 81);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 82);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 82);
INSERT INTO garn_har_farge VALUES ('Drops', 'Belle', 82);
INSERT INTO garn_har_farge VALUES ('Drops', 'Bomull-Lin', 82);
INSERT INTO garn_har_farge VALUES ('Drops', 'Loves You 9', 82);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 82);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 83);
INSERT INTO garn_har_farge VALUES ('Drops', 'Soft Tweed', 83);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 84);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 85);
INSERT INTO garn_har_farge VALUES ('Drops', 'Loves You 9', 85);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 86);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 87);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 87);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 88);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 88);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 89);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 90);
INSERT INTO garn_har_farge VALUES ('Drops', 'Belle', 90);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 91);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 91);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 91);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 91);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 92);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 93);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 94);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 94);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 95);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 95);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 96);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 97);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 98);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 99);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 99);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 100);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 101);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 102);
INSERT INTO garn_har_farge VALUES ('Drops', 'Soft Tweed', 102);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 103);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 104);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 105);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 105);
INSERT INTO garn_har_farge VALUES ('Drops', 'Melody', 105);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 105);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 105);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 106);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 107);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 108);
INSERT INTO garn_har_farge VALUES ('Drops', 'Alpaca', 109);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 110);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 111);
INSERT INTO garn_har_farge VALUES ('Drops', 'Soft Tweed', 111);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 112);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 113);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 114);
INSERT INTO garn_har_farge VALUES ('Drops', 'Big Merino', 114);
INSERT INTO garn_har_farge VALUES ('Drops', 'Loves You 9', 114);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 114);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 114);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 115);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 116);
INSERT INTO garn_har_farge VALUES ('Drops', 'Andes', 117);
INSERT INTO garn_har_farge VALUES ('Drops', 'Loves You 9', 118);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 119);
INSERT INTO garn_har_farge VALUES ('Drops', 'Soft Tweed', 119);
INSERT INTO garn_har_farge VALUES ('Drops', 'Polaris', 120);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 121);
INSERT INTO garn_har_farge VALUES ('Drops', 'Soft Tweed', 122);
INSERT INTO garn_har_farge VALUES ('Drops', 'Soft Tweed', 123);
INSERT INTO garn_har_farge VALUES ('Drops', 'Melody', 124);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 125);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 126);
INSERT INTO garn_har_farge VALUES ('Drops', 'Big Merino', 127);
INSERT INTO garn_har_farge VALUES ('Drops', 'Loves You 9', 128);
INSERT INTO garn_har_farge VALUES ('Drops', 'Belle', 129);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 129);
INSERT INTO garn_har_farge VALUES ('Drops', 'Soft Tweed', 130);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 131);
INSERT INTO garn_har_farge VALUES ('Drops', 'Wish', 132);
INSERT INTO garn_har_farge VALUES ('Drops', 'Big Merino', 132);
INSERT INTO garn_har_farge VALUES ('Drops', 'Puna', 133);
INSERT INTO garn_har_farge VALUES ('Drops', 'Soft Tweed', 134);
INSERT INTO garn_har_farge VALUES ('Drops', 'Glitter', 135);
INSERT INTO garn_har_farge VALUES ('Drops', 'Soft Tweed', 136);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 137);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 138);
INSERT INTO garn_har_farge VALUES ('Drops', 'Wish', 139);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 139);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 140);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 141);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 141);
INSERT INTO garn_har_farge VALUES ('Drops', 'Wish', 142);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 142);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 143);
INSERT INTO garn_har_farge VALUES ('Drops', 'Belle', 144);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 145);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 146);
INSERT INTO garn_har_farge VALUES ('Drops', 'Soft Tweed', 146);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 147);
INSERT INTO garn_har_farge VALUES ('Drops', 'Big Merino', 148);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 148);
INSERT INTO garn_har_farge VALUES ('Drops', 'Loves You 9', 149);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 150);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 151);
INSERT INTO garn_har_farge VALUES ('Drops', 'Belle', 152);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 152);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 152);
INSERT INTO garn_har_farge VALUES ('Drops', 'Belle', 153);
INSERT INTO garn_har_farge VALUES ('Drops', 'Big Merino', 154);
INSERT INTO garn_har_farge VALUES ('Drops', 'Melody', 155);
INSERT INTO garn_har_farge VALUES ('Drops', 'Soft Tweed', 155);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 155);
INSERT INTO garn_har_farge VALUES ('Drops', 'Belle', 156);
INSERT INTO garn_har_farge VALUES ('Drops', 'Big Merino', 157);
INSERT INTO garn_har_farge VALUES ('Drops', 'Melody', 158);
INSERT INTO garn_har_farge VALUES ('Drops', 'Bomull-Lin', 159);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 160);
INSERT INTO garn_har_farge VALUES ('Drops', 'Belle', 161);
INSERT INTO garn_har_farge VALUES ('Drops', 'Melody', 161);
INSERT INTO garn_har_farge VALUES ('Drops', 'Wish', 162);
INSERT INTO garn_har_farge VALUES ('Drops', 'Big Merino', 163);
INSERT INTO garn_har_farge VALUES ('Drops', 'Soft Tweed', 164);
INSERT INTO garn_har_farge VALUES ('Drops', 'Belle', 165);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 166);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 167);
INSERT INTO garn_har_farge VALUES ('Drops', 'Big Merino', 168);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 168);
INSERT INTO garn_har_farge VALUES ('Drops', 'Daisy', 168);
INSERT INTO garn_har_farge VALUES ('Drops', 'Soft Tweed', 169);
INSERT INTO garn_har_farge VALUES ('Drops', 'Soft Tweed', 170);
INSERT INTO garn_har_farge VALUES ('Drops', 'Delight', 171);
INSERT INTO garn_har_farge VALUES ('Drops', 'Belle', 172);
INSERT INTO garn_har_farge VALUES ('Drops', 'Melody', 172);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 173);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 173);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 174);
INSERT INTO garn_har_farge VALUES ('Drops', 'Belle', 175);
INSERT INTO garn_har_farge VALUES ('Drops', 'Bomull-Lin', 175);
INSERT INTO garn_har_farge VALUES ('Drops', 'Loves You 9', 175);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 175);
INSERT INTO garn_har_farge VALUES ('Drops', 'Soft Tweed', 175);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 176);
INSERT INTO garn_har_farge VALUES ('Drops', 'Belle', 177);
INSERT INTO garn_har_farge VALUES ('Drops', 'Nord', 178);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 179);
INSERT INTO garn_har_farge VALUES ('Drops', 'Wish', 180);
INSERT INTO garn_har_farge VALUES ('Drops', 'Belle', 181);
INSERT INTO garn_har_farge VALUES ('Drops', 'Soft Tweed', 182);
INSERT INTO garn_har_farge VALUES ('Drops', 'Wish', 183);
INSERT INTO garn_har_farge VALUES ('Drops', 'Soft Tweed', 184);
INSERT INTO garn_har_farge VALUES ('Drops', 'Melody', 185);
INSERT INTO garn_har_farge VALUES ('Drops', 'Loves You 9', 186);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 186);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 187);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 188);
INSERT INTO garn_har_farge VALUES ('Drops', 'Glitter', 189);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 190);
INSERT INTO garn_har_farge VALUES ('Drops', 'Melody', 191);
INSERT INTO garn_har_farge VALUES ('Drops', 'Melody', 192);
INSERT INTO garn_har_farge VALUES ('Drops', 'Cotton Merino', 192);
INSERT INTO garn_har_farge VALUES ('Drops', 'Sky', 193);
