INSERT INTO ovelser VALUES(1, "Jogging", "Løper i en moderat hastighet over en lengre periode");
INSERT INTO ovelser VALUES(2, "Arm-og-beinsvinger", "Arm- og beinsvinger er en oppvarmingsøvelse der du svinger armene og beina i en kontrollert bevegelse");
INSERT INTO ovelser VALUES(3, "Nedkjøling", "Nedkjøling og stretching for området som er blitt trent");
INSERT INTO ovelser VALUES(4, "Løping", "Løping er en form for kardiovaskulær trening der du beveger deg fremover ved å løpe i et jevnt tempo");
INSERT INTO ovelser VALUES(5, "Yoga", "Yoga er en praksis som kombinerer fysiske øvelser, pusteteknikker og meditasjon for å fremme fysisk og mental helse");
INSERT INTO ovelser VALUES(6, "Svømming", "Svømming er en aerobic treningsform der du beveger deg gjennom vann ved å bruke arm- og beinbevegelser");
INSERT INTO ovelser VALUES(7, "Spasertur", "En spasertur er en enkel og lavintensiv form for fysisk aktivitet der du går i ditt eget tempo");
INSERT INTO ovelser VALUES(8, "Sykling", "Sykling er en form for kardiovaskulær trening der du beveger deg ved å tråkke på pedaler og sykle enten innendørs på en stasjonær sykkel eller utendørs på en sykkelvei eller terreng");
INSERT INTO ovelser VALUES(9, "Benkpress", "Benkpress er en øvelse der du ligger på en flat benk og løfter en vektstang opp og ned ved å bøye og strekke armene");
INSERT INTO ovelser VALUES(10, "Roing-med-stang-eller-manualer", "Roing med stang eller manualer innebærer å trekke en vektstang eller manualer mot kroppen din mens du står eller sitter");
INSERT INTO ovelser VALUES(11, "Skulderpress", "Skulderpress er en styrkeøvelse der du løfter en vektstang eller manualer over hodet ved å strekke armene oppover");
INSERT INTO ovelser VALUES(12, "Bicepscurls", "Bicepscurls er en øvelse der du løfter vektstang eller manualer ved å bøye albuene og kontrahere bicepsmuskelen");
INSERT INTO ovelser VALUES(13, "Triceps-dips", "Triceps dips er en øvelse der du senker og løfter kroppen ved å bøye og strekke albuene, mens du støtter deg på en benk eller stol.");
INSERT INTO ovelser VALUES(14, "Knebøy", "Knebøy er en styrkeøvelse der du senker kroppen nedover ved å bøye knærne og hoftene, og deretter strekker deg opp igjen til stående posisjon.");
INSERT INTO ovelser VALUES(15, "Utfall", "Utfall er en øvelse der du tar et stort skritt fremover med ett ben, senker kroppen nedover ved å bøye begge knærne, og deretter presser deg tilbake til stående posisjon.");
INSERT INTO ovelser VALUES(16, "Rumensk-markløft", "Rumensk markløft er en øvelse der du holder en vektstang foran deg med strake armer, bøyer deg fremover i hoftene mens du holder bena strake, og deretter strekker deg opp igjen til oppreist posisjon ved å bruke baken og baksiden av lårene.");
INSERT INTO ovelser VALUES(17, "Leg-curls", "Leg curls er en øvelse der du ligger på en benk med ansiktet nedover, og bøyer beina ved knærne mens du løfter vekten mot baken ved å trekke hælene mot setet.");
INSERT INTO ovelser VALUES(18, "Leg-press", "Leg press er en øvelse der du sitter i en maskin med vektstangen hvilende på skuldrene, og deretter presser vekten opp ved å strekke ut bena mens du sitter.");
INSERT INTO ovelser VALUES(19, "Valgfri-aktivitet", "Valgfri aktivitet som ikke er for krevende, f.eks. en rolig sykkeltur eller en tur i naturen"); 
INSERT INTO ovelser VALUES(20, "Full-hvile/lett-aktivitet", "Full hviledag eller veldig lett aktivitet som rolig stretching eller en kort spasertur");
INSERT INTO ovelser VALUES(21, "Lett-aktivitet", "Lett aktivitet som yoga, svømming eller en spasertur.");
INSERT INTO ovelser VALUES(22, "Sykling/Svømming", "Velg selv om du vil sykle eller ta en svømmetur");